### ISSUE TITLE
Unable to activate extension with error

### ISSUE THREAD

**Issue by zachberger** [curdeveryday/vscode-m5stack-mpy#13]
```
[2021-08-18 19:00:53.736] [exthost] [error] Activating extension curdeveryday.vscode-m5stack-mpy failed due to an error:
[2021-08-18 19:00:53.736] [exthost] [error] Error: Could not locate the bindings file. Tried:
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/Debug/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/Release/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/out/Debug/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/Debug/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/out/Release/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/Release/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/default/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/compiled/14.16.0/darwin/arm64/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/addon-build/release/install-root/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/addon-build/debug/install-root/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/addon-build/default/install-root/detection.node
 → /Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/lib/binding/node-v89-darwin-arm64/detection.node
	at bindings (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/bindings/bindings.js:126:9)
	at Object.<anonymous> (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/index.js:13:37)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/node-usb-native/lib/detector.js:6:12)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/node-usb-native/lib/index.js:1:82)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/src/serialport.js:9:24)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/src/portlist.js:2:28)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/zachberger/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/extension.js:2:18)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at v._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:26057)
	at v._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12603)
	at v._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11704)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

**Comment by darul75** [comment]
Got an idea on how to solve this type of issue I got also but would need to get confirmation from the author. I will raise a PR rewriting the whole soon. I keep you in touch.

**Comment by darul75** [comment]
hello @zachberger for the sake of it even if you are not using it a lot could you try updating to the latest version 1.1.3 and let us know if that works for you know. thanks.

**Comment by zachberger** [comment]
Hi @darul75 -

I no longer see this issue! 

Thanks

**Comment by darul75** [comment]
@curdeveryday issue can be closed.

**Comment by AustinSnow** [comment]
Hello,
I'm having the same issue on VSCode Version: 1.66.0 with the latest extension, 1.1.4. I'm running NodeJS v16.13.1 on a Apple M1 Pro and with Monterey.

Is there a fix for this?
-Thank you
-Austin

**Comment by Mandred** [comment]
Similar Problem with a fresh setup of 1.85.1 and 1.1.10

![image](https://github.com/curdeveryday/vscode-m5stack-mpy/assets/18084518/c8cbc627-b876-4176-a30d-f114e1903bbe)


`workbench.desktop.main.js:sourcemap:2017 Activating extension 'curdeveryday.vscode-m5stack-mpy' failed: Could not locate the bindings file. Tried:
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\build\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\build\Debug\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\build\Release\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\out\Debug\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\Debug\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\out\Release\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\Release\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\build\default\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\compiled\18.15.0\win32\x64\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\addon-build\release\install-root\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\addon-build\debug\install-root\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\addon-build\default\install-root\bindings.node
 → c:\Users\mirko\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.10\node_modules\@serialport\bindings\lib\binding\node-v116-win32-x64\bindings.node.
$onExtensionActivationError @ workbench.desktop.main.js:sourcemap:2017
`

**Comment by kinoshita-lab** [comment]
Hello, I found the solution for this issue.
I refered following article written in Japanese.
https://zenn.dev/s3pt3mb3r/articles/54b41a21c1a4e8

It tells to type following command(I found it must be run at the root of extension installed folder, I mean for example  something like `.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.1.10` but varies accordingly with the version you have installed.

```
npm rebuild @serialport/bindings
```

If it fails, run the above command again after trying below:
```
npm install -g prebuild-install
npm install node-addon-api
```

@Mandred , I can solve the problem with the procedures above.  Please try it if you are interested.

**Comment by hitokuno** [comment]
`rebuild @serialport/bindings` did not solve the issue.

Mac OS 12.5 (M1)
VS Code Version: 1.85.2 (Universal)
node v16.20.2, v17.9.1, v18.19.0, v20.11.0, v21.6.1
