### ISSUE TITLE
Activating extension failed on MacOS running on Apple Silicon (M1)

### ISSUE THREAD

**Issue by dbuch-github** [curdeveryday/vscode-m5stack-mpy#14]
Activating extension curdeveryday.vscode-m5stack-mpy failed due to an error:

2021-08-19 18:16:18.734] [exthost] [error] Activating extension curdeveryday.vscode-m5stack-mpy failed due to an error:
[2021-08-19 18:16:18.735] [exthost] [error] Error: Could not locate the bindings file. Tried:
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/Debug/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/Release/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/out/Debug/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/Debug/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/out/Release/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/Release/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/build/default/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/compiled/14.16.0/darwin/arm64/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/addon-build/release/install-root/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/addon-build/debug/install-root/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/addon-build/default/install-root/detection.node
 → /Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/lib/binding/node-v89-darwin-arm64/detection.node
	at bindings (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/bindings/bindings.js:126:9)
	at Object.<anonymous> (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/usb-detection/index.js:13:37)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/node-usb-native/lib/detector.js:6:12)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/node_modules/node-usb-native/lib/index.js:1:82)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/src/serialport.js:9:24)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/src/portlist.js:2:28)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/Users/dbuch/.vscode/extensions/curdeveryday.vscode-m5stack-mpy-1.0.11/extension.js:2:18)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at v._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:26057)
	at v._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12603)
	at v._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11704)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
	at async Promise.all (index 0)

**Comment by darul75** [comment]
hello @dbuch-github can you please try installing latest version, it should not take long and let us know if we can close this case. thank you.

**Comment by AustinSnow** [comment]
Hello,
I'm having the same issue on VSCode Version: 1.66.0 with the latest extension, 1.1.4.  I'm running NodeJS v16.13.1 on a Apple M1 Pro and with Monterey.

Is there a fix for this?
-Thank you
-Austin
