### ISSUE TITLE
No M5Stack button

### ISSUE THREAD

**Issue by gobilicious** [curdeveryday/vscode-m5stack-mpy#32]
With the latest version of VSCode and the extension the m5stack button doesn't appear and the extension has an error starting up.  Seems like this has been an issue before but wasn't sure if this is an extension issue or an environment issue.

Thanks

vscode-m5stack-mpy version 1.1.7

VSCode:

Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

Seems to be an issue with bindings.node not being found:

[2022-04-06 09:45:12.425] [exthost] [error] Activating extension curdeveryday.vscode-m5stack-mpy failed due to an error:
[2022-04-06 09:45:12.425] [exthost] [error] Error: Could not locate the bindings file. Tried:
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\build\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\build\Debug\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\build\Release\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\out\Debug\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\Debug\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\out\Release\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\Release\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\build\default\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\compiled\16.13.0\win32\x64\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\addon-build\release\install-root\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\addon-build\debug\install-root\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\addon-build\default\install-root\bindings.node
 → c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\lib\binding\node-v101-win32-x64\bindings.node
	at bindings (c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\bindings\bindings.js:126:9)
	at Object.<anonymous> (c:\Users\user\.vscode\extensions\curdeveryday.vscode-m5stack-mpy-1.1.4\node_modules\@serialport\bindings\lib\win32.js:1:98)

**Comment by darul75** [comment]
Got an idea, will see if I got time to patch current version as I think it is due to the NodeJS version you got combined with a newer version of VSCode.
